CREATE TABLE IF NOT EXISTS endpoint_hit (
    hit_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    app varchar(100),
    uri varchar(100),
    ip varchar(50),
    timestamp TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT hit_id_pk PRIMARY KEY (hit_id)
);